export type CodeLayoutTokenDetail =
	| 'function'
	| 'const'
	| 'let'
	| 'param-colon'
	| 'return-type'
	| 'type-name'
	| 'brace-open'
	| 'brace-close'
	| 'paren-open'
	| 'paren-close'
	| 'angle-open'
	| 'angle-close'
	| 'comma'
	| 'dot'
	| 'equals'
	| 'pipe'
	| 'ampersand'
	| 'arrow'
	| 'extends'
	| 'readonly'
	| 'optional'
	| 'generic-param'
	| 'accessor-get'
	| 'accessor-set'
	| string; // allow fallback escape hatch
