export const ENTITY_SEARCH_LIMIT = 100;

export const SEARCH_MATCH_SCORE_ENTITY_NAME_VERBATIM = 10;
export const SEARCH_MATCH_SCORE_ENTITY_DESCRIPTION_VERBATIM = 5;
export const SEARCH_MATCH_SCORE_ENTITY_NAME_GREEDY = 2;
export const SEARCH_MATCH_SCORE_ENTITY_DESCRIPTION_GREEDY = 1;

export const SEARCH_MATCH_SCORE_SYMBOL_NAME_VERBATIM = 10;
export const SEARCH_MATCH_SCORE_SYMBOL_DESCRIPTION_VERBATIM = 5;
export const SEARCH_MATCH_SCORE_SYMBOL_NAME_GREEDY = 2;
export const SEARCH_MATCH_SCORE_SYMBOL_DESCRIPTION_GREEDY = 1;
